export const COUNTRY_LIST = [
    { code: "CN", name: "China", label: "(CN) 中国大陆" },
    { code: "JP", name: "Japan", label: "(JP) 日本" },
    { code: "US", name: "USA", label: "(US) USA" },
    { code: "UK", name: "UK", label: "(UK) UK" },
    { code: "FR", name: "France", label: "(FR) France" },
    { code: "DE", name: "Germany", label: "(DE) Deutschland" },
    { code: "IN", name: "India", label: "(IN) India" },
    { code: "CA", name: "Canada", label: "(CA) Canada" },
    { code: "AU", name: "Australia", label: "(AU) Australia" },
    { code: "TW", name: "Taiwan", label: "(TW) 台湾" },
    { code: "HK", name: "Hong Kong", label: "(HK) 香港" },
    { code: "BR", name: "Brazil", label: "(BR) Brasil" },
    { code: "RU", name: "Russia", label: "(RU) Россия" },
    { code: "ZA", name: "South Africa", label: "(ZA) South Africa" },
    { code: "MX", name: "Mexico", label: "(MX) México" },
    { code: "IT", name: "Italy", label: "(IT) Italia" },
    { code: "ES", name: "Spain", label: "(ES) España" },
    { code: "KR", name: "South Korea", label: "(KR) 대한민국" },
    { code: "NL", name: "Netherlands", label: "(NL) Nederland" },
    { code: "SE", name: "Sweden", label: "(SE) Sverige" },
    { code: "CH", name: "Switzerland", label: "(CH) Schweiz" },
    { code: "BE", name: "Belgium", label: "(BE) België" },
    { code: "AR", name: "Argentina", label: "(AR) Argentina" },
];